// Generated by CoffeeScript 1.10.0
(function() {
  var $, _, defaultApply, fillwidth, imagesLoaded, jqueryFillwidthLite;

  $ = (typeof window !== "undefined" && window !== null ? window.$ : void 0) || null;

  _ = (typeof window !== "undefined" && window !== null ? window._ : void 0) || null;

  imagesLoaded = (typeof window !== "undefined" && window !== null ? window.imagesLoaded : void 0) || null;

  jqueryFillwidthLite = function(a, b, c) {
    $ || ($ = a);
    _ || (_ = b);
    imagesLoaded || (imagesLoaded = c);
    return $.fn.fillwidthLite = function(options) {
      if (options == null) {
        options = {};
      }
      return fillwidth($(this), options.targetHeight || 500, options.done || function() {}, options.apply || defaultApply, options.gutterSize || 0, options.dontResizeUp || false);
    };
  };

  defaultApply = function(img) {
    return img.$el.width(img.width);
  };

  fillwidth = function($list, targetHeight, done, apply, gutterSize, dontResizeUp) {
    var $imgs;
    $imgs = $list.find('img');
    return imagesLoaded($list[0], (function(_this) {
      return function() {
        var dir, i, img, imgs, imgsWidth, j, k, l, len, len1, len2, len3, o, p, resizeHeight, totalWhitespace, widthDiff;
        imgs = $imgs.map(function() {
          return {
            width: $(this).width(),
            height: $(this).height(),
            $el: $(this)
          };
        }).toArray();
        imgsWidth = function() {
          return _.reduce(_.map(imgs, function(i) {
            return i.width;
          }), function(m, n) {
            return m + n;
          });
        };
        totalWhitespace = function() {
          return (imgs.length - 1) * gutterSize;
        };
        widthDiff = function() {
          return $list.width() - imgsWidth() - totalWhitespace();
        };
        resizeHeight = function(img, dir) {
          img.width += (img.width / img.height) * dir;
          return img.height += dir;
        };
        for (j = 0, len = imgs.length; j < len; j++) {
          img = imgs[j];
          img.width = img.width * (targetHeight / img.height);
          img.height = targetHeight;
        }
        if (widthDiff() > 0 && dontResizeUp) {
          return done(imgs);
        }
        dir = widthDiff() < 0 ? -1 : 1;
        for (i = k = 0; k <= 999; i = ++k) {
          for (l = 0, len1 = imgs.length; l < len1; l++) {
            img = imgs[l];
            resizeHeight(img, dir);
            if (widthDiff() > 1) {
              break;
            }
          }
          if (widthDiff() > 1) {
            break;
          }
        }
        for (o = 0, len2 = imgs.length; o < len2; o++) {
          img = imgs[o];
          img.width = Math.floor(img.width);
          img.height = Math.floor(img.height);
          if (widthDiff() === 0) {
            break;
          }
        }
        for (i = p = 0, len3 = imgs.length; p < len3; i = ++p) {
          img = imgs[i];
          apply(img, i, gutterSize);
        }
        return done(imgs);
      };
    })(this));
  };

  if (typeof module !== "undefined" && module !== null ? module.exports : void 0) {
    module.exports = jqueryFillwidthLite;
  } else {
    if (typeof window !== "undefined" && window !== null) {
      window.jqueryFillwidthLite = jqueryFillwidthLite;
    }
  }

}).call(this);
